/**
 * Writes lib/i18n/match-kind-words.ts: for every kind of pair but the couple, every sentence of the couple's report
 * wording (t.match) that reads differently for that kind, as a whole sentence, in English and in Russian. The
 * sentences come from applying each kind's swap list (lib/i18n/match-*.ts) to the base wording. Whole sentences
 * are what the translation service translates, so every language gets "partnership report" said properly, instead
 * of a phrase swap that only matches English and Russian text. Run after changing t.match or a swap list:
 *
 *   npm run match:words
 */
import { writeFileSync } from "node:fs";
import { flatten } from "../lib/i18n/flat";
import { en } from "../lib/i18n/en";
import { ru } from "../lib/i18n/ru";
import { MATCH_KINDS, swapWords, type MatchKind } from "../lib/match-kind";

const out: Record<"en" | "ru", Record<MatchKind, Record<string, string>>> = { en: {} as never, ru: {} as never };
const dicts = { en, ru };
// These are written out per kind by hand (KindWords) and set last by matchWords(), so they are not generated.
const EXPLICIT = new Set(["title", "lead", "eyebrow", "categoriesTitle", "partnerFallback", "partnerName"]);
for (const kind of MATCH_KINDS) {
  const changed = new Set<string>();
  const flats = { en: flatten(en.match), ru: flatten(ru.match) };
  for (const lang of ["en", "ru"] as const) {
    const words = dicts[lang].content.match.kinds[kind];
    for (const [path, text] of Object.entries(flats[lang])) if (!EXPLICIT.has(path) && swapWords(text, words) !== text) changed.add(path);
  }
  // Both languages carry the same keys (the dictionary shape test insists), the base sentence where a language's swaps left it alone.
  for (const lang of ["en", "ru"] as const) {
    const words = dicts[lang].content.match.kinds[kind];
    out[lang][kind] = Object.fromEntries([...changed].sort().map((path) => [path, swapWords(flats[lang][path], words)]));
  }
}

const file = `/** GENERATED by scripts/match-kind-words.mts; do not edit. The couple's report wording, said whole for each kind of pair. */
import type { MatchKind } from "../match-kind";

export const matchKindWordsEn: Record<MatchKind, Record<string, string>> = ${JSON.stringify(out.en, null, 2)};

export const matchKindWordsRu: Record<MatchKind, Record<string, string>> = ${JSON.stringify(out.ru, null, 2)};
`;
writeFileSync(new URL("../lib/i18n/match-kind-words.ts", import.meta.url), file);
for (const kind of MATCH_KINDS) console.log(kind, "sentences:", Object.keys(out.en[kind]).length);
