/** GENERATED by scripts/match-kind-words.mts; do not edit. The couple's report wording, said whole for each kind of pair. */
import type { MatchKind } from "../match-kind";

export const matchKindWordsEn: Record<MatchKind, Record<string, string>> = {
  "couple": {},
  "business": {
    "haveRecording": "I have their voice or video",
    "order": "Invite my business partner",
    "stepHow": "How do we get {name}'s voice?",
    "switchToUpload": "Have a recording of {name}? Upload it instead →"
  },
  "colleagues": {
    "haveRecording": "I have their voice or video",
    "order": "Invite my colleague",
    "stepHow": "How do we get {name}'s voice?",
    "switchToUpload": "Have a recording of {name}? Upload it instead →"
  },
  "family": {
    "haveRecording": "I have their voice or video",
    "order": "Invite my family member",
    "stepHow": "How do we get {name}'s voice?",
    "switchToUpload": "Have a recording of {name}? Upload it instead →"
  },
  "friends": {
    "haveRecording": "I have their voice or video",
    "order": "Invite my friend",
    "stepHow": "How do we get {name}'s voice?",
    "switchToUpload": "Have a recording of {name}? Upload it instead →"
  }
};

export const matchKindWordsRu: Record<MatchKind, Record<string, string>> = {
  "couple": {},
  "business": {
    "haveRecording": "У меня есть голос или видео бизнес-партнёра",
    "order": "Пригласить бизнес-партнёра",
    "stepHow": "Как мы получим голос бизнес-партнёра ({name})?",
    "switchToUpload": "Есть запись бизнес-партнёра? Загрузите её →"
  },
  "colleagues": {
    "haveRecording": "У меня есть голос или видео коллеги",
    "order": "Пригласить коллегу",
    "stepHow": "Как мы получим голос коллеги ({name})?",
    "switchToUpload": "Есть запись коллеги? Загрузите её →"
  },
  "family": {
    "haveRecording": "У меня есть голос или видео близкого",
    "order": "Пригласить близкого",
    "stepHow": "Как мы получим голос близкого ({name})?",
    "switchToUpload": "Есть запись близкого? Загрузите её →"
  },
  "friends": {
    "haveRecording": "У меня есть голос или видео друга",
    "order": "Пригласить друга",
    "stepHow": "Как мы получим голос друга ({name})?",
    "switchToUpload": "Есть запись друга? Загрузите её →"
  }
};
